dist: trusty
addons:
  apt:
    sources:
     - ubuntu-toolchain-r-test
    packages:
     - coreutils
     - g++-4.8
     - gdb
language: node_js
node_js:
  - "5"
  - "4"
  - "0.12"
  - "0.10"

script:
  - make test